version: '{build}'

skip_tags: true

install: []

environment:
  matrix:
    - VSVERSION: Visual Studio 16 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

platform:
  - Win32
  - x64

configuration:
  - Debug
  - RelWithDebInfo
  - MinSizeRel
  - Release

build_script:
  - md build
  - cd build
  - if "%PLATFORM%"=="x64" cmake -G "%VSVERSION%" -A "x64" ../test
  - if "%PLATFORM%"=="Win32" cmake -G "%VSVERSION%" -A "Win32" ../test
  - msbuild /m /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%" tqueue_test.sln
  - copy %CONFIGURATION%\tqueue_test.exe tqueue_test.exe

test_script:
  - tqueue_test.exe